/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  aux_sym_label_token1 = 2,
  aux_sym_label_token2 = 3,
  anon_sym_COLON = 4,
  anon_sym_SECTION = 5,
  anon_sym_COMMA = 6,
  anon_sym_ENDSECTION = 7,
  aux_sym_section_name_token1 = 8,
  aux_sym_section_type_token1 = 9,
  aux_sym_section_type_token2 = 10,
  aux_sym_section_type_token3 = 11,
  anon_sym_OAM = 12,
  anon_sym_LBRACK = 13,
  aux_sym__section_address_token1 = 14,
  anon_sym_RBRACK = 15,
  sym__section_bank_opt = 16,
  sym__section_align_opt = 17,
  anon_sym_PUSHS = 18,
  anon_sym_POPS = 19,
  sym__line_comment = 20,
  sym__block_comment = 21,
  sym_program = 22,
  sym__item = 23,
  sym_label = 24,
  sym_section = 25,
  sym__section_start = 26,
  sym__section_end = 27,
  sym_section_name = 28,
  sym_section_type = 29,
  sym__section_address = 30,
  sym_section_option = 31,
  sym_stack = 32,
  sym_comment = 33,
  aux_sym_program_repeat1 = 34,
  aux_sym_program_repeat2 = 35,
  aux_sym__section_start_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [aux_sym_label_token1] = "label_token1",
  [aux_sym_label_token2] = "label_token2",
  [anon_sym_COLON] = ":",
  [anon_sym_SECTION] = "SECTION",
  [anon_sym_COMMA] = ",",
  [anon_sym_ENDSECTION] = "ENDSECTION",
  [aux_sym_section_name_token1] = "section_name_token1",
  [aux_sym_section_type_token1] = "section_type_token1",
  [aux_sym_section_type_token2] = "section_type_token2",
  [aux_sym_section_type_token3] = "section_type_token3",
  [anon_sym_OAM] = "OAM",
  [anon_sym_LBRACK] = "[",
  [aux_sym__section_address_token1] = "_section_address_token1",
  [anon_sym_RBRACK] = "]",
  [sym__section_bank_opt] = "_section_bank_opt",
  [sym__section_align_opt] = "_section_align_opt",
  [anon_sym_PUSHS] = "PUSHS",
  [anon_sym_POPS] = "POPS",
  [sym__line_comment] = "_line_comment",
  [sym__block_comment] = "_block_comment",
  [sym_program] = "program",
  [sym__item] = "_item",
  [sym_label] = "label",
  [sym_section] = "section",
  [sym__section_start] = "_section_start",
  [sym__section_end] = "_section_end",
  [sym_section_name] = "section_name",
  [sym_section_type] = "section_type",
  [sym__section_address] = "_section_address",
  [sym_section_option] = "section_option",
  [sym_stack] = "stack",
  [sym_comment] = "comment",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_program_repeat2] = "program_repeat2",
  [aux_sym__section_start_repeat1] = "_section_start_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_label_token1] = aux_sym_label_token1,
  [aux_sym_label_token2] = aux_sym_label_token2,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SECTION] = anon_sym_SECTION,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_ENDSECTION] = anon_sym_ENDSECTION,
  [aux_sym_section_name_token1] = aux_sym_section_name_token1,
  [aux_sym_section_type_token1] = aux_sym_section_type_token1,
  [aux_sym_section_type_token2] = aux_sym_section_type_token2,
  [aux_sym_section_type_token3] = aux_sym_section_type_token3,
  [anon_sym_OAM] = anon_sym_OAM,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym__section_address_token1] = aux_sym__section_address_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym__section_bank_opt] = sym__section_bank_opt,
  [sym__section_align_opt] = sym__section_align_opt,
  [anon_sym_PUSHS] = anon_sym_PUSHS,
  [anon_sym_POPS] = anon_sym_POPS,
  [sym__line_comment] = sym__line_comment,
  [sym__block_comment] = sym__block_comment,
  [sym_program] = sym_program,
  [sym__item] = sym__item,
  [sym_label] = sym_label,
  [sym_section] = sym_section,
  [sym__section_start] = sym__section_start,
  [sym__section_end] = sym__section_end,
  [sym_section_name] = sym_section_name,
  [sym_section_type] = sym_section_type,
  [sym__section_address] = sym__section_address,
  [sym_section_option] = sym_section_option,
  [sym_stack] = sym_stack,
  [sym_comment] = sym_comment,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_program_repeat2] = aux_sym_program_repeat2,
  [aux_sym__section_start_repeat1] = aux_sym__section_start_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_label_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_label_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SECTION] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ENDSECTION] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_section_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_type_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_type_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_type_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_OAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__section_address_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym__section_bank_opt] = {
    .visible = false,
    .named = true,
  },
  [sym__section_align_opt] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PUSHS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POPS] = {
    .visible = true,
    .named = false,
  },
  [sym__line_comment] = {
    .visible = false,
    .named = true,
  },
  [sym__block_comment] = {
    .visible = false,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym__section_start] = {
    .visible = false,
    .named = true,
  },
  [sym__section_end] = {
    .visible = false,
    .named = true,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [sym_section_type] = {
    .visible = true,
    .named = true,
  },
  [sym__section_address] = {
    .visible = false,
    .named = true,
  },
  [sym_section_option] = {
    .visible = true,
    .named = true,
  },
  [sym_stack] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__section_start_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(72);
      ADVANCE_MAP(
        '\n', 73,
        '"', 2,
        '$', 69,
        ',', 81,
        '.', 70,
        '/', 3,
        ':', 79,
        ';', 102,
        'A', 23,
        'B', 8,
        'E', 28,
        'O', 7,
        'P', 33,
        'R', 34,
        'S', 14,
        'W', 39,
        '[', 92,
        ']', 97,
        'H', 38,
        'V', 38,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('C' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(83);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(103);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == ',') ADVANCE(1);
      if (lookahead == ']') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'A') ADVANCE(24);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'A') ADVANCE(29);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'A') ADVANCE(26);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 10:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'A') ADVANCE(27);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'C') ADVANCE(44);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 12:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'C') ADVANCE(45);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 13:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'D') ADVANCE(41);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 14:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'E') ADVANCE(11);
      if (lookahead == 'R') ADVANCE(9);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 15:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'E') ADVANCE(11);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 16:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'E') ADVANCE(12);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 17:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'G') ADVANCE(32);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 18:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'H') ADVANCE(43);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 19:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'I') ADVANCE(17);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 20:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'I') ADVANCE(35);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 21:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'I') ADVANCE(36);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 22:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'K') ADVANCE(46);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 23:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'L') ADVANCE(19);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 24:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'M') ADVANCE(91);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 25:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'M') ADVANCE(48);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 26:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'M') ADVANCE(89);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 27:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'M') ADVANCE(49);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 28:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'N') ADVANCE(13);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 29:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'N') ADVANCE(22);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 30:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'N') ADVANCE(80);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 31:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'N') ADVANCE(82);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 32:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'N') ADVANCE(47);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 33:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'O') ADVANCE(37);
      if (lookahead == 'U') ADVANCE(40);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 34:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'O') ADVANCE(25);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 35:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'O') ADVANCE(30);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 36:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'O') ADVANCE(31);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 37:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'P') ADVANCE(42);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 38:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'R') ADVANCE(9);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 39:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'R') ADVANCE(10);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 40:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'S') ADVANCE(18);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 41:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'S') ADVANCE(16);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 42:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'S') ADVANCE(101);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 43:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'S') ADVANCE(100);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 44:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'T') ADVANCE(20);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 45:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == 'T') ADVANCE(21);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 46:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == '[') ADVANCE(66);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 47:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == '[') ADVANCE(67);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 48:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == '0' ||
          lookahead == 'X') ADVANCE(85);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('1' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 49:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == '0' ||
          lookahead == 'X') ADVANCE(87);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('1' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 50:
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 51:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ';') ADVANCE(102);
      if (lookahead == 'O') ADVANCE(52);
      if (lookahead == 'R') ADVANCE(59);
      if (lookahead == 'W') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(51);
      if (lookahead == 'H' ||
          lookahead == 'S' ||
          lookahead == 'V') ADVANCE(61);
      END_STATE();
    case 52:
      if (lookahead == 'A') ADVANCE(55);
      END_STATE();
    case 53:
      if (lookahead == 'A') ADVANCE(58);
      END_STATE();
    case 54:
      if (lookahead == 'A') ADVANCE(57);
      END_STATE();
    case 55:
      if (lookahead == 'M') ADVANCE(90);
      END_STATE();
    case 56:
      if (lookahead == 'M') ADVANCE(64);
      END_STATE();
    case 57:
      if (lookahead == 'M') ADVANCE(88);
      END_STATE();
    case 58:
      if (lookahead == 'M') ADVANCE(65);
      END_STATE();
    case 59:
      if (lookahead == 'O') ADVANCE(56);
      END_STATE();
    case 60:
      if (lookahead == 'R') ADVANCE(53);
      END_STATE();
    case 61:
      if (lookahead == 'R') ADVANCE(54);
      END_STATE();
    case 62:
      if (lookahead == ']') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 63:
      if (lookahead == ']') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      if (lookahead == '0' ||
          lookahead == 'X') ADVANCE(84);
      END_STATE();
    case 65:
      if (lookahead == '0' ||
          lookahead == 'X') ADVANCE(86);
      END_STATE();
    case 66:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 67:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 68:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 69:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(96);
      END_STATE();
    case 70:
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 71:
      if (eof) ADVANCE(72);
      ADVANCE_MAP(
        '\n', 73,
        '.', 70,
        '/', 3,
        ':', 79,
        ';', 102,
        'E', 28,
        'P', 33,
        'S', 15,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_label_token1);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_label_token1);
      if (lookahead == ':') ADVANCE(74);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_label_token2);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_label_token2);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_label_token2);
      if (lookahead == ':') ADVANCE(76);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_SECTION);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_ENDSECTION);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_section_name_token1);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_section_type_token1);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_section_type_token1);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_section_type_token2);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_section_type_token2);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_section_type_token3);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_section_type_token3);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_OAM);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_OAM);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym__section_address_token1);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym__section_address_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(93);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym__section_address_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(94);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym__section_address_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(95);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym__section_bank_opt);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym__section_align_opt);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_PUSHS);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_POPS);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == ':') ADVANCE(75);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym__line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym__block_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 71},
  [2] = {.lex_state = 71},
  [3] = {.lex_state = 71},
  [4] = {.lex_state = 71},
  [5] = {.lex_state = 71},
  [6] = {.lex_state = 71},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 51},
  [9] = {.lex_state = 51},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [aux_sym_label_token1] = ACTIONS(1),
    [aux_sym_label_token2] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SECTION] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_ENDSECTION] = ACTIONS(1),
    [aux_sym_section_name_token1] = ACTIONS(1),
    [aux_sym_section_type_token1] = ACTIONS(1),
    [aux_sym_section_type_token2] = ACTIONS(1),
    [aux_sym_section_type_token3] = ACTIONS(1),
    [anon_sym_OAM] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [aux_sym__section_address_token1] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym__section_bank_opt] = ACTIONS(1),
    [sym__section_align_opt] = ACTIONS(1),
    [anon_sym_PUSHS] = ACTIONS(1),
    [anon_sym_POPS] = ACTIONS(1),
    [sym__line_comment] = ACTIONS(3),
    [sym__block_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_program] = STATE(31),
    [sym__item] = STATE(11),
    [sym_label] = STATE(23),
    [sym_section] = STATE(23),
    [sym__section_start] = STATE(28),
    [sym__section_end] = STATE(28),
    [sym_stack] = STATE(23),
    [sym_comment] = STATE(1),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_label_token1] = ACTIONS(7),
    [aux_sym_label_token2] = ACTIONS(7),
    [anon_sym_COLON] = ACTIONS(7),
    [anon_sym_SECTION] = ACTIONS(9),
    [anon_sym_ENDSECTION] = ACTIONS(11),
    [anon_sym_PUSHS] = ACTIONS(13),
    [anon_sym_POPS] = ACTIONS(15),
    [sym__line_comment] = ACTIONS(3),
    [sym__block_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__item] = STATE(27),
    [sym_label] = STATE(23),
    [sym_section] = STATE(23),
    [sym__section_start] = STATE(28),
    [sym__section_end] = STATE(28),
    [sym_stack] = STATE(23),
    [sym_comment] = STATE(2),
    [aux_sym_program_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_LF] = ACTIONS(19),
    [aux_sym_label_token1] = ACTIONS(7),
    [aux_sym_label_token2] = ACTIONS(7),
    [anon_sym_COLON] = ACTIONS(7),
    [anon_sym_SECTION] = ACTIONS(9),
    [anon_sym_ENDSECTION] = ACTIONS(11),
    [anon_sym_PUSHS] = ACTIONS(13),
    [anon_sym_POPS] = ACTIONS(15),
    [sym__line_comment] = ACTIONS(3),
    [sym__block_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__item] = STATE(27),
    [sym_label] = STATE(23),
    [sym_section] = STATE(23),
    [sym__section_start] = STATE(28),
    [sym__section_end] = STATE(28),
    [sym_stack] = STATE(23),
    [sym_comment] = STATE(3),
    [aux_sym_program_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LF] = ACTIONS(19),
    [aux_sym_label_token1] = ACTIONS(7),
    [aux_sym_label_token2] = ACTIONS(7),
    [anon_sym_COLON] = ACTIONS(7),
    [anon_sym_SECTION] = ACTIONS(9),
    [anon_sym_ENDSECTION] = ACTIONS(11),
    [anon_sym_PUSHS] = ACTIONS(13),
    [anon_sym_POPS] = ACTIONS(15),
    [sym__line_comment] = ACTIONS(3),
    [sym__block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(9), 1,
      anon_sym_SECTION,
    ACTIONS(11), 1,
      anon_sym_ENDSECTION,
    ACTIONS(13), 1,
      anon_sym_PUSHS,
    ACTIONS(15), 1,
      anon_sym_POPS,
    ACTIONS(19), 1,
      anon_sym_LF,
    STATE(4), 1,
      sym_comment,
    STATE(5), 1,
      aux_sym_program_repeat1,
    STATE(27), 1,
      sym__item,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(28), 2,
      sym__section_start,
      sym__section_end,
    ACTIONS(7), 3,
      aux_sym_label_token1,
      aux_sym_label_token2,
      anon_sym_COLON,
    STATE(23), 3,
      sym_label,
      sym_section,
      sym_stack,
  [43] = 5,
    ACTIONS(25), 1,
      anon_sym_LF,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(5), 2,
      sym_comment,
      aux_sym_program_repeat1,
    ACTIONS(23), 4,
      ts_builtin_sym_end,
      aux_sym_label_token1,
      aux_sym_label_token2,
      anon_sym_COLON,
    ACTIONS(28), 4,
      anon_sym_SECTION,
      anon_sym_ENDSECTION,
      anon_sym_PUSHS,
      anon_sym_POPS,
  [67] = 4,
    STATE(6), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(32), 4,
      anon_sym_SECTION,
      anon_sym_ENDSECTION,
      anon_sym_PUSHS,
      anon_sym_POPS,
    ACTIONS(30), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      aux_sym_label_token1,
      aux_sym_label_token2,
      anon_sym_COLON,
  [88] = 5,
    ACTIONS(36), 1,
      anon_sym_LBRACK,
    STATE(7), 1,
      sym_comment,
    STATE(17), 1,
      sym__section_address,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(34), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [107] = 4,
    STATE(8), 1,
      sym_comment,
    STATE(26), 1,
      sym_section_type,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(38), 4,
      aux_sym_section_type_token1,
      aux_sym_section_type_token2,
      aux_sym_section_type_token3,
      anon_sym_OAM,
  [124] = 4,
    STATE(9), 1,
      sym_comment,
    STATE(12), 1,
      sym_section_type,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(38), 4,
      aux_sym_section_type_token1,
      aux_sym_section_type_token2,
      aux_sym_section_type_token3,
      anon_sym_OAM,
  [141] = 6,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_LF,
    STATE(3), 1,
      aux_sym_program_repeat1,
    STATE(10), 1,
      sym_comment,
    STATE(14), 1,
      aux_sym_program_repeat2,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [161] = 6,
    ACTIONS(19), 1,
      anon_sym_LF,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym_program_repeat1,
    STATE(10), 1,
      aux_sym_program_repeat2,
    STATE(11), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [181] = 5,
    ACTIONS(44), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      sym_comment,
    STATE(13), 1,
      aux_sym__section_start_repeat1,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [199] = 5,
    ACTIONS(44), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym__section_start_repeat1,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(46), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [217] = 5,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 1,
      anon_sym_LF,
    STATE(4), 1,
      aux_sym_program_repeat1,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(14), 2,
      sym_comment,
      aux_sym_program_repeat2,
  [235] = 4,
    ACTIONS(55), 1,
      anon_sym_COMMA,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(15), 2,
      sym_comment,
      aux_sym__section_start_repeat1,
  [251] = 3,
    STATE(16), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(58), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [264] = 3,
    STATE(17), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(60), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [277] = 3,
    STATE(18), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(62), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [290] = 3,
    STATE(19), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(53), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [303] = 4,
    STATE(19), 1,
      sym_section_option,
    STATE(20), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(64), 2,
      sym__section_bank_opt,
      sym__section_align_opt,
  [318] = 3,
    STATE(21), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [330] = 4,
    ACTIONS(68), 1,
      aux_sym_section_name_token1,
    STATE(22), 1,
      sym_comment,
    STATE(30), 1,
      sym_section_name,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [344] = 3,
    STATE(23), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [356] = 3,
    STATE(24), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [368] = 3,
    STATE(25), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [380] = 3,
    STATE(26), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [392] = 3,
    STATE(27), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [404] = 3,
    STATE(28), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(78), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [416] = 3,
    ACTIONS(80), 1,
      aux_sym_section_name_token1,
    STATE(29), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [427] = 3,
    ACTIONS(82), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [438] = 3,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    STATE(31), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [449] = 3,
    ACTIONS(86), 1,
      anon_sym_RBRACK,
    STATE(32), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [460] = 3,
    ACTIONS(88), 1,
      aux_sym__section_address_token1,
    STATE(33), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [471] = 3,
    ACTIONS(90), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [482] = 1,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 43,
  [SMALL_STATE(6)] = 67,
  [SMALL_STATE(7)] = 88,
  [SMALL_STATE(8)] = 107,
  [SMALL_STATE(9)] = 124,
  [SMALL_STATE(10)] = 141,
  [SMALL_STATE(11)] = 161,
  [SMALL_STATE(12)] = 181,
  [SMALL_STATE(13)] = 199,
  [SMALL_STATE(14)] = 217,
  [SMALL_STATE(15)] = 235,
  [SMALL_STATE(16)] = 251,
  [SMALL_STATE(17)] = 264,
  [SMALL_STATE(18)] = 277,
  [SMALL_STATE(19)] = 290,
  [SMALL_STATE(20)] = 303,
  [SMALL_STATE(21)] = 318,
  [SMALL_STATE(22)] = 330,
  [SMALL_STATE(23)] = 344,
  [SMALL_STATE(24)] = 356,
  [SMALL_STATE(25)] = 368,
  [SMALL_STATE(26)] = 380,
  [SMALL_STATE(27)] = 392,
  [SMALL_STATE(28)] = 404,
  [SMALL_STATE(29)] = 416,
  [SMALL_STATE(30)] = 427,
  [SMALL_STATE(31)] = 438,
  [SMALL_STATE(32)] = 449,
  [SMALL_STATE(33)] = 460,
  [SMALL_STATE(34)] = 471,
  [SMALL_STATE(35)] = 482,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 3, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_type, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__section_start, 4, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__section_start, 5, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat2, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat2, 2, 0, 0), SHIFT_REPEAT(6),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__section_start_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__section_start_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__section_address, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_type, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_option, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stack, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__section_end, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stack, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [84] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_name, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rgbds(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "rgbds",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
