/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_COLON = 2,
  anon_sym_COLON_COLON = 3,
  sym__global_label = 4,
  aux_sym__local_label_token1 = 5,
  anon_sym_SECTION = 6,
  aux_sym_section_token1 = 7,
  anon_sym_ENDSECTION = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_COMMA = 11,
  anon_sym_ROM0 = 12,
  anon_sym_ROMX = 13,
  anon_sym_VRAM = 14,
  anon_sym_SRAM = 15,
  anon_sym_WRAM0 = 16,
  anon_sym_WRAMX = 17,
  anon_sym_OAM = 18,
  anon_sym_HRAM = 19,
  aux_sym__sec_opts_token1 = 20,
  aux_sym__sec_opts_token2 = 21,
  sym__addr = 22,
  sym__line_comment = 23,
  sym__block_comment = 24,
  sym_program = 25,
  sym__item = 26,
  sym_label = 27,
  sym__local_label = 28,
  sym_section = 29,
  sym__sec_addr = 30,
  sym__sec_type = 31,
  sym__sec_opts = 32,
  sym_comment = 33,
  aux_sym_program_repeat1 = 34,
  aux_sym_program_repeat2 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_COLON] = ":",
  [anon_sym_COLON_COLON] = "::",
  [sym__global_label] = "_global_label",
  [aux_sym__local_label_token1] = "_local_label_token1",
  [anon_sym_SECTION] = "SECTION",
  [aux_sym_section_token1] = "section_token1",
  [anon_sym_ENDSECTION] = "ENDSECTION",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_ROM0] = "ROM0",
  [anon_sym_ROMX] = "ROMX",
  [anon_sym_VRAM] = "VRAM",
  [anon_sym_SRAM] = "SRAM",
  [anon_sym_WRAM0] = "WRAM0",
  [anon_sym_WRAMX] = "WRAMX",
  [anon_sym_OAM] = "OAM",
  [anon_sym_HRAM] = "HRAM",
  [aux_sym__sec_opts_token1] = "_sec_opts_token1",
  [aux_sym__sec_opts_token2] = "_sec_opts_token2",
  [sym__addr] = "_addr",
  [sym__line_comment] = "_line_comment",
  [sym__block_comment] = "_block_comment",
  [sym_program] = "program",
  [sym__item] = "_item",
  [sym_label] = "label",
  [sym__local_label] = "_local_label",
  [sym_section] = "section",
  [sym__sec_addr] = "_sec_addr",
  [sym__sec_type] = "_sec_type",
  [sym__sec_opts] = "_sec_opts",
  [sym_comment] = "comment",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_program_repeat2] = "program_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym__global_label] = sym__global_label,
  [aux_sym__local_label_token1] = aux_sym__local_label_token1,
  [anon_sym_SECTION] = anon_sym_SECTION,
  [aux_sym_section_token1] = aux_sym_section_token1,
  [anon_sym_ENDSECTION] = anon_sym_ENDSECTION,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_ROM0] = anon_sym_ROM0,
  [anon_sym_ROMX] = anon_sym_ROMX,
  [anon_sym_VRAM] = anon_sym_VRAM,
  [anon_sym_SRAM] = anon_sym_SRAM,
  [anon_sym_WRAM0] = anon_sym_WRAM0,
  [anon_sym_WRAMX] = anon_sym_WRAMX,
  [anon_sym_OAM] = anon_sym_OAM,
  [anon_sym_HRAM] = anon_sym_HRAM,
  [aux_sym__sec_opts_token1] = aux_sym__sec_opts_token1,
  [aux_sym__sec_opts_token2] = aux_sym__sec_opts_token2,
  [sym__addr] = sym__addr,
  [sym__line_comment] = sym__line_comment,
  [sym__block_comment] = sym__block_comment,
  [sym_program] = sym_program,
  [sym__item] = sym__item,
  [sym_label] = sym_label,
  [sym__local_label] = sym__local_label,
  [sym_section] = sym_section,
  [sym__sec_addr] = sym__sec_addr,
  [sym__sec_type] = sym__sec_type,
  [sym__sec_opts] = sym__sec_opts,
  [sym_comment] = sym_comment,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_program_repeat2] = aux_sym_program_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym__global_label] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__local_label_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SECTION] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_section_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_ENDSECTION] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ROM0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ROMX] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_VRAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SRAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_WRAM0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_WRAMX] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HRAM] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__sec_opts_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sec_opts_token2] = {
    .visible = false,
    .named = false,
  },
  [sym__addr] = {
    .visible = false,
    .named = true,
  },
  [sym__line_comment] = {
    .visible = false,
    .named = true,
  },
  [sym__block_comment] = {
    .visible = false,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym__local_label] = {
    .visible = false,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym__sec_addr] = {
    .visible = false,
    .named = true,
  },
  [sym__sec_type] = {
    .visible = false,
    .named = true,
  },
  [sym__sec_opts] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(55);
      ADVANCE_MAP(
        '\n', 56,
        '"', 3,
        '$', 48,
        ',', 94,
        '.', 52,
        '/', 4,
        ':', 57,
        ';', 117,
        'B', 11,
        'E', 32,
        'H', 37,
        'O', 12,
        'R', 35,
        'S', 20,
        'V', 42,
        'W', 43,
        '[', 92,
        ']', 93,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == 'A') ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(51);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(90);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(118);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == ',') ADVANCE(2);
      if (lookahead == ']') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        '/', 4,
        ';', 117,
        'B', 15,
        'H', 38,
        'O', 14,
        'R', 36,
        'S', 39,
        'V', 40,
        'W', 41,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 9:
      if (lookahead == '0') ADVANCE(95);
      if (lookahead == 'X') ADVANCE(97);
      END_STATE();
    case 10:
      if (lookahead == '0') ADVANCE(103);
      if (lookahead == 'X') ADVANCE(105);
      END_STATE();
    case 11:
      if (lookahead == 'A') ADVANCE(78);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 12:
      if (lookahead == 'A') ADVANCE(72);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 13:
      if (lookahead == 'A') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'A') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 'A') ADVANCE(34);
      END_STATE();
    case 16:
      if (lookahead == 'A') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 'A') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'A') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 'A') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 'E') ADVANCE(65);
      if (lookahead == 'R') ADVANCE(62);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 21:
      if (lookahead == 'E') ADVANCE(65);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 22:
      if (lookahead == 'G') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'I') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'K') ADVANCE(44);
      END_STATE();
    case 25:
      if (lookahead == 'L') ADVANCE(23);
      END_STATE();
    case 26:
      if (lookahead == 'M') ADVANCE(107);
      END_STATE();
    case 27:
      if (lookahead == 'M') ADVANCE(9);
      END_STATE();
    case 28:
      if (lookahead == 'M') ADVANCE(109);
      END_STATE();
    case 29:
      if (lookahead == 'M') ADVANCE(101);
      END_STATE();
    case 30:
      if (lookahead == 'M') ADVANCE(99);
      END_STATE();
    case 31:
      if (lookahead == 'M') ADVANCE(10);
      END_STATE();
    case 32:
      if (lookahead == 'N') ADVANCE(67);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 33:
      if (lookahead == 'N') ADVANCE(45);
      END_STATE();
    case 34:
      if (lookahead == 'N') ADVANCE(24);
      END_STATE();
    case 35:
      if (lookahead == 'O') ADVANCE(73);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 36:
      if (lookahead == 'O') ADVANCE(27);
      END_STATE();
    case 37:
      if (lookahead == 'R') ADVANCE(61);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 38:
      if (lookahead == 'R') ADVANCE(16);
      END_STATE();
    case 39:
      if (lookahead == 'R') ADVANCE(17);
      END_STATE();
    case 40:
      if (lookahead == 'R') ADVANCE(18);
      END_STATE();
    case 41:
      if (lookahead == 'R') ADVANCE(19);
      END_STATE();
    case 42:
      if (lookahead == 'R') ADVANCE(63);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 43:
      if (lookahead == 'R') ADVANCE(64);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 44:
      if (lookahead == '[') ADVANCE(49);
      END_STATE();
    case 45:
      if (lookahead == '[') ADVANCE(50);
      END_STATE();
    case 46:
      if (lookahead == ']') ADVANCE(111);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 47:
      if (lookahead == ']') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 53:
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 54:
      if (eof) ADVANCE(55);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == ',') ADVANCE(1);
      if (lookahead == '.') ADVANCE(52);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ';') ADVANCE(117);
      if (lookahead == 'E') ADVANCE(32);
      if (lookahead == 'S') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == '0') ADVANCE(96);
      if (lookahead == 'X') ADVANCE(98);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == '0') ADVANCE(104);
      if (lookahead == 'X') ADVANCE(106);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'A') ADVANCE(74);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'A') ADVANCE(75);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'A') ADVANCE(76);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'A') ADVANCE(77);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'C') ADVANCE(84);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'C') ADVANCE(85);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'D') ADVANCE(83);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'E') ADVANCE(66);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'I') ADVANCE(81);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'I') ADVANCE(82);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'K') ADVANCE(86);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'M') ADVANCE(108);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'M') ADVANCE(59);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'M') ADVANCE(110);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'M') ADVANCE(102);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'M') ADVANCE(100);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'M') ADVANCE(60);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'N') ADVANCE(71);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'N') ADVANCE(89);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'N') ADVANCE(91);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'O') ADVANCE(79);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'O') ADVANCE(80);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'S') ADVANCE(68);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'T') ADVANCE(69);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == 'T') ADVANCE(70);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == '[') ADVANCE(49);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym__global_label);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym__local_label_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_SECTION);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_section_token1);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_ENDSECTION);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_ROM0);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_ROM0);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_ROMX);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_ROMX);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_VRAM);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_VRAM);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_SRAM);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_SRAM);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_WRAM0);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_WRAM0);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_WRAMX);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_WRAMX);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_OAM);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_OAM);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_HRAM);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_HRAM);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym__sec_opts_token1);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym__sec_opts_token2);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym__addr);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym__addr);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym__addr);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym__addr);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym__line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym__block_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 54},
  [2] = {.lex_state = 54},
  [3] = {.lex_state = 54},
  [4] = {.lex_state = 54},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 54},
  [7] = {.lex_state = 54},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 54},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 0},
  [32] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym__global_label] = ACTIONS(1),
    [aux_sym__local_label_token1] = ACTIONS(1),
    [anon_sym_SECTION] = ACTIONS(1),
    [aux_sym_section_token1] = ACTIONS(1),
    [anon_sym_ENDSECTION] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_ROM0] = ACTIONS(1),
    [anon_sym_ROMX] = ACTIONS(1),
    [anon_sym_VRAM] = ACTIONS(1),
    [anon_sym_SRAM] = ACTIONS(1),
    [anon_sym_WRAM0] = ACTIONS(1),
    [anon_sym_WRAMX] = ACTIONS(1),
    [anon_sym_OAM] = ACTIONS(1),
    [anon_sym_HRAM] = ACTIONS(1),
    [aux_sym__sec_opts_token1] = ACTIONS(1),
    [sym__addr] = ACTIONS(1),
    [sym__line_comment] = ACTIONS(3),
    [sym__block_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_program] = STATE(29),
    [sym__item] = STATE(14),
    [sym_label] = STATE(25),
    [sym__local_label] = STATE(10),
    [sym_section] = STATE(25),
    [sym_comment] = STATE(1),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__global_label] = ACTIONS(7),
    [aux_sym__local_label_token1] = ACTIONS(9),
    [anon_sym_SECTION] = ACTIONS(11),
    [anon_sym_ENDSECTION] = ACTIONS(13),
    [sym__line_comment] = ACTIONS(3),
    [sym__block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(7), 1,
      sym__global_label,
    ACTIONS(9), 1,
      aux_sym__local_label_token1,
    ACTIONS(11), 1,
      anon_sym_SECTION,
    ACTIONS(13), 1,
      anon_sym_ENDSECTION,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_LF,
    STATE(2), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_program_repeat1,
    STATE(10), 1,
      sym__local_label,
    STATE(22), 1,
      sym__item,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(25), 2,
      sym_label,
      sym_section,
  [39] = 12,
    ACTIONS(7), 1,
      sym__global_label,
    ACTIONS(9), 1,
      aux_sym__local_label_token1,
    ACTIONS(11), 1,
      anon_sym_SECTION,
    ACTIONS(13), 1,
      anon_sym_ENDSECTION,
    ACTIONS(17), 1,
      anon_sym_LF,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_program_repeat1,
    STATE(10), 1,
      sym__local_label,
    STATE(22), 1,
      sym__item,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(25), 2,
      sym_label,
      sym_section,
  [78] = 11,
    ACTIONS(7), 1,
      sym__global_label,
    ACTIONS(9), 1,
      aux_sym__local_label_token1,
    ACTIONS(11), 1,
      anon_sym_SECTION,
    ACTIONS(13), 1,
      anon_sym_ENDSECTION,
    ACTIONS(17), 1,
      anon_sym_LF,
    STATE(4), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_program_repeat1,
    STATE(10), 1,
      sym__local_label,
    STATE(22), 1,
      sym__item,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(25), 2,
      sym_label,
      sym_section,
  [114] = 3,
    STATE(5), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(21), 8,
      anon_sym_ROM0,
      anon_sym_ROMX,
      anon_sym_VRAM,
      anon_sym_SRAM,
      anon_sym_WRAM0,
      anon_sym_WRAMX,
      anon_sym_OAM,
      anon_sym_HRAM,
  [132] = 5,
    ACTIONS(25), 1,
      anon_sym_LF,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      aux_sym__local_label_token1,
    STATE(6), 2,
      sym_comment,
      aux_sym_program_repeat1,
    ACTIONS(28), 3,
      sym__global_label,
      anon_sym_SECTION,
      anon_sym_ENDSECTION,
  [153] = 4,
    STATE(7), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(30), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      aux_sym__local_label_token1,
    ACTIONS(32), 3,
      sym__global_label,
      anon_sym_SECTION,
      anon_sym_ENDSECTION,
  [171] = 5,
    ACTIONS(36), 1,
      anon_sym_LBRACK,
    STATE(8), 1,
      sym_comment,
    STATE(17), 1,
      sym__sec_addr,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(34), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [190] = 6,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_LF,
    STATE(3), 1,
      aux_sym_program_repeat1,
    STATE(9), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_program_repeat2,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [210] = 5,
    ACTIONS(40), 1,
      anon_sym_COLON,
    ACTIONS(42), 1,
      anon_sym_COLON_COLON,
    STATE(10), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [228] = 5,
    ACTIONS(46), 1,
      anon_sym_COMMA,
    STATE(11), 1,
      sym_comment,
    STATE(24), 1,
      sym__sec_opts,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(44), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [246] = 4,
    ACTIONS(50), 1,
      anon_sym_COLON,
    STATE(12), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(48), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COLON_COLON,
  [262] = 4,
    ACTIONS(54), 1,
      anon_sym_COLON,
    STATE(13), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(52), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COLON_COLON,
  [278] = 6,
    ACTIONS(17), 1,
      anon_sym_LF,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym_program_repeat1,
    STATE(9), 1,
      aux_sym_program_repeat2,
    STATE(14), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [298] = 5,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      anon_sym_LF,
    STATE(4), 1,
      aux_sym_program_repeat1,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(15), 2,
      sym_comment,
      aux_sym_program_repeat2,
  [316] = 5,
    ACTIONS(40), 1,
      anon_sym_COLON,
    ACTIONS(42), 1,
      anon_sym_COLON_COLON,
    ACTIONS(63), 1,
      aux_sym__local_label_token1,
    STATE(16), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [333] = 3,
    STATE(17), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [346] = 4,
    ACTIONS(69), 1,
      aux_sym__sec_opts_token2,
    STATE(18), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [361] = 3,
    STATE(19), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(71), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_COMMA,
  [374] = 3,
    STATE(20), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [386] = 4,
    ACTIONS(75), 1,
      anon_sym_COMMA,
    STATE(11), 1,
      sym__sec_type,
    STATE(21), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [400] = 3,
    STATE(22), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [412] = 3,
    STATE(23), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [424] = 3,
    STATE(24), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [436] = 3,
    STATE(25), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [448] = 3,
    STATE(26), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [460] = 3,
    ACTIONS(85), 1,
      aux_sym_section_token1,
    STATE(27), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [471] = 3,
    ACTIONS(87), 1,
      sym__addr,
    STATE(28), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [482] = 3,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    STATE(29), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [493] = 3,
    ACTIONS(91), 1,
      aux_sym__sec_opts_token1,
    STATE(30), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [504] = 3,
    ACTIONS(93), 1,
      anon_sym_RBRACK,
    STATE(31), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym__line_comment,
      sym__block_comment,
  [515] = 1,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 114,
  [SMALL_STATE(6)] = 132,
  [SMALL_STATE(7)] = 153,
  [SMALL_STATE(8)] = 171,
  [SMALL_STATE(9)] = 190,
  [SMALL_STATE(10)] = 210,
  [SMALL_STATE(11)] = 228,
  [SMALL_STATE(12)] = 246,
  [SMALL_STATE(13)] = 262,
  [SMALL_STATE(14)] = 278,
  [SMALL_STATE(15)] = 298,
  [SMALL_STATE(16)] = 316,
  [SMALL_STATE(17)] = 333,
  [SMALL_STATE(18)] = 346,
  [SMALL_STATE(19)] = 361,
  [SMALL_STATE(20)] = 374,
  [SMALL_STATE(21)] = 386,
  [SMALL_STATE(22)] = 400,
  [SMALL_STATE(23)] = 412,
  [SMALL_STATE(24)] = 424,
  [SMALL_STATE(25)] = 436,
  [SMALL_STATE(26)] = 448,
  [SMALL_STATE(27)] = 460,
  [SMALL_STATE(28)] = 471,
  [SMALL_STATE(29)] = 482,
  [SMALL_STATE(30)] = 493,
  [SMALL_STATE(31)] = 504,
  [SMALL_STATE(32)] = 515,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 3, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sec_type, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__local_label, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__local_label, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__local_label, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__local_label, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat2, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat2, 2, 0, 0), SHIFT_REPEAT(7),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sec_type, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sec_opts, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sec_addr, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sec_opts, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [89] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rgbds(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "rgbds",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
